-- MySQL Script generated by MySQL Workbench
-- Fri Oct 16 21:18:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User_Authentication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_Authentication` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_Authentication` (
  `ID` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `emailid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin_Authentication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admin_Authentication` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Admin_Authentication` (
  `AdminID` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AdminID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal_Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Personal_Info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Personal_Info` (
  `User_Authentication_ID` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `middlename` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `DOB` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `SIN` VARCHAR(45) NULL,
  INDEX `fk_table1_User_Authentication_idx` (`User_Authentication_ID` ASC) VISIBLE,
  PRIMARY KEY (`User_Authentication_ID`),
  CONSTRAINT `fk_table1_User_Authentication`
    FOREIGN KEY (`User_Authentication_ID`)
    REFERENCES `mydb`.`User_Authentication` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account_Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Account_Info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Account_Info` (
  `User_Authentication_ID` INT NOT NULL,
  `accountholdername` VARCHAR(45) NOT NULL,
  `accountnumber` VARCHAR(45) NOT NULL,
  `accountbalance` BIGINT(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  INDEX `fk_Account_Info_User_Authentication1_idx` (`User_Authentication_ID` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`User_Authentication_ID`),
  CONSTRAINT `fk_Account_Info_User_Authentication1`
    FOREIGN KEY (`User_Authentication_ID`)
    REFERENCES `mydb`.`User_Authentication` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`History` ;

CREATE TABLE IF NOT EXISTS `mydb`.`History` (
  `User_Authentication_ID` INT NOT NULL,
  `amount` INT(8) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `toemail` VARCHAR(45) NULL,
  `date` DATETIME NOT NULL,
  `fromemail` VARCHAR(45) NULL,
  `comments` VARCHAR(45) NULL,
  INDEX `fk_History_User_Authentication1_idx` (`User_Authentication_ID` ASC) VISIBLE,
  PRIMARY KEY (`User_Authentication_ID`),
  CONSTRAINT `fk_History_User_Authentication1`
    FOREIGN KEY (`User_Authentication_ID`)
    REFERENCES `mydb`.`User_Authentication` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SignUp_Req`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SignUp_Req` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SignUp_Req` (
  `ID` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `emailid` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `DOB` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `SIN` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
